services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:ro
    environment:
      - GIN_MODE=release
    networks:
      - git-report-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - git-report-network

networks:
  git-report-network:
    driver: bridge